# Generated by go2rpm 1
%bcond_without check

# https://github.com/mrjones/oauth
%global goipath         github.com/mrjones/oauth
%global commit          126b3521945043926caf026a3b969659b6a38d23

%gometa

%global common_description %{expand:
OAuth 1.0 implementation in go (golang).}

%global golicenses      MIT-LICENSE.txt
%global godocs          examples README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        OAuth 1.0 implementation in go (golang)

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sat Jan 25 16:50:15 CET 2020 Marcel Metz <mmetz@adrian-broher.net> - 0-0.1.20200125git126b352
- Initial package
